### ISSUE TITLE
Could you t.l.c the less in this thing please?

### ISSUE THREAD

**Issue by oliverfoster** [cgkineo/adapt-contentObjectTransition#1]
Works with latest framework v5.5.0

**Comment by guywillis** [comment]
@oliverfoster I've tweaked the Less in a fairly loose sense and checked the transitions work for the RTL version too. Would you mind double checking it all still works for you please?

**Comment by oliverfoster** [comment]
Awesome, that you, will have a test today and get back to you! :D

**Comment by oliverfoster** [comment]
Superb, thanks @guywillis
